resource.AddFile( "sound/advert.wav" )
resource.AddFile( "sound/doormod_disrupted.wav" )
resource.AddFile( "sound/doormod_loop.wav" )
resource.AddFile( "sound/weldspark.wav" )

resource.AddFile( "materials/vgui/gradient-bl.vmt" )
resource.AddFile( "materials/vgui/gradient-bl.vtf" )
resource.AddFile( "materials/vgui/gradient-br.vmt" )
resource.AddFile( "materials/vgui/gradient-br.vtf" )
resource.AddFile( "materials/vgui/gradient-l.vmt" )

resource.AddFile( "materials/hudicons/c4.vmt" )
resource.AddFile( "materials/hudicons/c4.vtf" )
resource.AddFile( "materials/hudicons/fnade.vmt" )
resource.AddFile( "materials/hudicons/fnade.vtf" )
resource.AddFile( "materials/hudicons/health.vmt" )
resource.AddFile( "materials/hudicons/health.vtf" )
resource.AddFile( "materials/hudicons/health2.vmt" )
resource.AddFile( "materials/hudicons/health2.vtf" )
resource.AddFile( "materials/hudicons/henade.vmt" )
resource.AddFile( "materials/hudicons/henade.vtf" )
resource.AddFile( "materials/hudicons/shield.vmt" )
resource.AddFile( "materials/hudicons/shield.vtf" )
resource.AddFile( "materials/hudicons/snade.vmt" )
resource.AddFile( "materials/hudicons/snade.vtf" )

resource.AddFile( "materials/toolicons/propspawn.vmt" )
resource.AddFile( "materials/toolicons/propspawn.vtf" )
resource.AddFile( "materials/toolicons/remover.vmt" )
resource.AddFile( "materials/toolicons/remover.vtf" )
resource.AddFile( "materials/toolicons/repair.vmt" )
resource.AddFile( "materials/toolicons/repair.vtf" )
resource.AddFile( "materials/toolicons/spawnpoint.vmt" )
resource.AddFile( "materials/toolicons/spawnpoint.vtf" )
resource.AddFile( "materials/toolicons/ammocrate_closed.vmt" )
resource.AddFile( "materials/toolicons/ammocrate_closed.vtf" )
resource.AddFile( "materials/toolicons/ammocrate_open.vmt" )
resource.AddFile( "materials/toolicons/ammocrate_open.vtf" )

resource.AddFile( "materials/blood/blood_spray.vmt" )
resource.AddFile( "materials/blood/blood_spray.vtf" )
resource.AddFile( "materials/blood/dying.vmt" )
resource.AddFile( "materials/blood/dying.vtf" )
resource.AddFile( "materials/blood/bsplatv1.vmt" )
resource.AddFile( "materials/blood/bsplatv1.vtf" )

resource.AddFile( "materials/scope/scope_normal.vmt" )
resource.AddFile( "materials/scope/scope_normal.vtf" )

resource.AddFile( "materials/scope/acog_reticle.vtf" )
resource.AddFile( "materials/scope/acog_reticle.vmt" )

resource.AddFile( "materials/doormod_blocked.vmt" )
resource.AddFile( "materials/doormod_unblocked.vmt" )

resource.AddFile( "materials/tool_radialbg.vmt" )
resource.AddFile( "materials/tool_radialbg.vtf" )

resource.AddFile( "materials/tool_radialselect.vmt" )
resource.AddFile( "materials/tool_radialselect.vtf" )

resource.AddFile( "materials/vignette.vmt" )
resource.AddFile( "materials/vignette.vtf" )

-- Explosion / Hit effects
resource.AddFile( "materials/refract_ring.vmt" )
resource.AddFile( "materials/refract_ring.vtf" )

resource.AddFile( "materials/effects/dust.vmt" )
resource.AddFile( "materials/effects/dust2.vmt" )
resource.AddFile( "materials/effects/dust.vtf" )
resource.AddFile( "materials/effects/dust2.vtf" )

-- Toolgun Shoot
resource.AddFile( "sound/weapons/alyx_gun/alyx_gun_fire3.wav" )
resource.AddFile( "sound/weapons/alyx_gun/alyx_gun_fire4.wav" )

-- Ammo Crate
resource.AddFile( "models/Items/ammocrate_smg2.mdl" )
resource.AddFile( "materials/models/Items/ammocrate_smg1.vmt" )
resource.AddFile( "materials/models/Items/ammocrate_smg1.vtf" )
resource.AddFile( "materials/models/Items/ammocrate_smg2.vmt" )
resource.AddFile( "materials/models/Items/ammocrate_smg2.vtf" )

-- Hats
resource.AddFile( "models/player/items/demo/crown.mdl" )
resource.AddFile( "models/player/items/scout/scout_ttg_max.mdl" )
resource.AddFile( "models/props_2fort/hardhat001.mdl" )

resource.AddFile( "materials/models/player/items/all_class/ttg_max.vmt" )
resource.AddFile( "materials/models/player/items/all_class/ttg_max.vtf" )
resource.AddFile( "materials/models/player/items/all_class/ttg_max_dx8.vtf" )
resource.AddFile( "materials/models/player/items/demo/crown.vmt" )
resource.AddFile( "materials/models/player/items/demo/crown.vtf" )
resource.AddFile( "materials/models/player/items/demo/crown_blu.vtf" )
resource.AddFile( "materials/models/props_2fort/hardhat001.vmt" )
resource.AddFile( "materials/models/props_2fort/hardhat001.vtf" )

resource.AddFile( "models/weapons/v_slam.mdl" )
resource.AddFile( "models/weapons/w_slam.mdl" )

-- Map resources
resource.AddFile( "materials/Concrete/concretewall075a.vmt" )
resource.AddFile( "materials/Concrete/concretewall075a.vtf" )

resource.AddFile( "models/props_foliage/rock_forest01a.mdl"  )
resource.AddFile( "models/props_foliage/rock_forest01b.mdl"  )
resource.AddFile( "models/props_foliage/rock_forest01c.mdl"  )
resource.AddFile( "models/props_foliage/rock_forest01d.mdl"  )
resource.AddFile( "models/props_foliage/rock_forest02.mdl"   )
resource.AddFile( "models/props_foliage/rock_forest03.mdl"   )
resource.AddFile( "models/props_foliage/rock_forest04.mdl"   )

resource.AddFile( "models/props_foliage/Tree_pine04.mdl"   )
resource.AddFile( "models/props_foliage/Tree_pine05.mdl"   )
resource.AddFile( "models/props_foliage/Tree_pine06.mdl"   )
resource.AddFile( "models/props_foliage/Tree_pine_large.mdl"   )

resource.AddFile( "materials/models/props_foliage/forestrock01.vmt" )
resource.AddFile( "materials/models/props_foliage/forestrock01.vtf")
resource.AddFile( "materials/models/props_foliage/forestrock01_normal.vtf")
resource.AddFile( "materials/models/props_foliage/forestrock_cluster01.vmt")
resource.AddFile( "materials/models/props_foliage/forestrock_cluster01.vtf")
resource.AddFile( "materials/models/props_foliage/forestrock_cluster01_normal.vtf")
resource.AddFile( "materials/models/props_foliage/forestrock_cluster02.vmt")
resource.AddFile( "materials/models/props_foliage/forestrock_cluster02.vtf")
resource.AddFile( "materials/models/props_foliage/forestrock_cluster02_normal.vtf")
resource.AddFile( "materials/models/props_foliage/forestrock_single01.vmt")
resource.AddFile( "materials/models/props_foliage/forestrock_single01.vtf")


resource.AddFile( "models/props_foliage/forestrock_cluster01.mdl")
resource.AddFile( "models/props_foliage/forestrock_cluster02.mdl")
resource.AddFile( "models/props_foliage/forestrock_single01.mdl" )
resource.AddFile( "models/props_foliage/grass_cluster01.mdl" )
resource.AddFile( "models/props_foliage/grass_cluster01a.mdl" )

resource.AddFile( "materials/models/props_foliage/tree_pine_01_branches.vmt")
resource.AddFile( "materials/models/props_foliage/tree_pine_01_branches.vtf")
resource.AddFile( "materials/models/props_foliage/tree_pine_cards_01.vmt")
resource.AddFile( "materials/models/props_foliage/tree_pine_cards_01.vtf")
resource.AddFile( "materials/models/props_foliage/tree_deciduous_01a_trunk.vmt")
resource.AddFile( "materials/models/props_foliage/tree_deciduous_01a_trunk.vtf")

resource.AddFile( "models/Cliffs/rocks_large02_veg.mdl" )
resource.AddFile( "models/Cliffs/rocks_medium01_veg.mdl" )
resource.AddFile( "models/Cliffs/rocks_medium02_veg.mdl" )
resource.AddFile( "models/Cliffs/rocks_medium03_veg.mdl" )
resource.AddFile( "models/Cliffs/rocks_small02_veg.mdl" )

resource.AddFile( "materials/models/Cliffs/Rocks01.vmt")
resource.AddFile( "materials/models/Cliffs/Rocks01.vtf")
resource.AddFile( "materials/models/Cliffs/rocks_vegetation.vmt")
resource.AddFile( "materials/models/Cliffs/Rocks_vegetation.vtf")
resource.AddFile( "materials/models/Cliffs/Rocks02.vmt")
resource.AddFile( "materials/models/Cliffs/Rocks02.vtf") 
resource.AddFile( "materials/models/props_foliage/grass_clusters.vmf")
resource.AddFile( "materials/models/props_foliage/grass_clusters.vtf")

resource.AddFile( "materials/toolicons/BG.vtf")
resource.AddFile( "materials/toolicons/BG.vmt")
resource.AddFile( "materials/screen/weaponcrate.vtf")
resource.AddFile( "materials/screen/weaponcrate.vmt")
resource.AddFile( "materials/screen/propspawn.vtf")
resource.AddFile( "materials/screen/propspawn.vmt")
resource.AddFile( "materials/screen/repair.vtf")
resource.AddFile( "materials/screen/repair.vmt")
resource.AddFile( "materials/screen/remover.vtf")
resource.AddFile( "materials/screen/remover.vmt")
resource.AddFile( "materials/screen/mobilesp.vtf")
resource.AddFile( "materials/screen/mobilesp.vmt")

resource.AddFile( "sound/hit1.wav")
resource.AddFile( "sound/hit2.wav")
resource.AddFile( "sound/hit3.wav")
resource.AddFile( "materials/hitdetection2.vmt")
resource.AddFile( "materials/hitdetection2.vtf")
resource.AddFile( "resource/cs.ttf" )
